name: ta-lib
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ta-lib
  - sphinxcontrib-programoutput
  - sphinx_rtd_theme
  - pip:
     - "--editable=git+https://git@github.com/Cryptrality/backtester.git@main#egg=cryptrality"